apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
  labels:
    app: otel-demo
    managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1: Official OpenTelemetry Demo Helm Chart
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-demo
      targetRevision: 0.32.7  # Latest stable version
      helm:
        releaseName: otel-demo
        # Use our custom values from GitOps repo
        valueFiles:
          - $values/apps/otel-demo/values.yaml

    # Source 2: GitOps repo for values file
    - repoURL: ${repo_url}
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
