apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraforge-root
  namespace: argocd
  labels:
    app: root
    managed-by: opentofu
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: ${repo_url}
    targetRevision: main
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
