# SMK Application - Secrets Configuration
# Uses External Secrets Operator to sync from AWS Secrets Manager
#
# Secrets are stored in AWS Secrets Manager:
# - prod/smk/db-password
# - prod/smk/api-key
# - prod/smk/jwt-secret

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smk-secrets
  namespace: smk
  labels:
    app.kubernetes.io/name: smk
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: smk-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: smk

  data:
    # Database Password
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/smk/db-password

    # API Keys
    - secretKey: API_KEY
      remoteRef:
        key: prod/smk/api-key

    # JWT Secret
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod/smk/jwt-secret

    # Third-party integrations (optional)
    # - secretKey: STRIPE_API_KEY
    #   remoteRef:
    #     key: prod/smk/stripe-api-key

---
# ClusterSecretStore (Create once for all apps)
# This should be created by terraform/monitoring-addons.tf
# Uncomment if needed:
#
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: aws-secretsmanager
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: eu-west-1
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: external-secrets
#             namespace: external-secrets
