# Sonsuz Enerji Application - Helm Values
# GitOps Configuration for Deployment

nameOverride: "sonsuzenerji"
fullnameOverride: "sonsuzenerji"

image:
  repository: 715841344657.dkr.ecr.eu-west-1.amazonaws.com/sonsuzenerji
  tag: "latest"
  pullPolicy: Always

replicaCount: 2

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: sonsuz.ticarethanem.net
  hosts:
    - host: sonsuz.ticarethanem.net
      paths:
        - path: /
          pathType: Prefix

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 5

envFrom:
  - configMapRef:
      name: sonsuzenerji-config
  - secretRef:
      name: sonsuzenerji-secrets

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
  - name: APP_NAME
    value: "sonsuzenerji"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/path: "/metrics"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
